name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production..."
          echo "TODO: Add your deployment steps here"
          echo "Examples:"
          echo "- Deploy to Vercel: vercel --prod"
          echo "- Deploy to Netlify: netlify deploy --prod --dir=dist"
          echo "- Deploy to Fly.io: fly deploy"
          echo "- Deploy to Railway: railway deploy"
          echo ""
          echo "Make sure to set up the following environment variables:"
          echo "- NEXT_PUBLIC_SUPABASE_URL"
          echo "- NEXT_PUBLIC_SUPABASE_ANON_KEY"
          echo "- SUPABASE_SERVICE_ROLE_KEY"
          echo "- STRIPE_SECRET_KEY"
          echo "- And other required environment variables"

      - name: Notify deployment
        run: |
          echo "✅ Deployment completed successfully!"
          echo "Version: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
